import jsPDF from "jspdf";
import "jspdf-autotable";

const generateReport = (result, formData, forecastData, alerts) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const today = new Date().toLocaleDateString();

    // --- Header ---
    doc.setFillColor(59, 130, 246); // Blue header
    doc.rect(0, 0, pageWidth, 40, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Climate Disease Predictor", 20, 20);

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text("AI-Powered Health Assessment Report", 20, 30);
    doc.text(`Date: ${today}`, pageWidth - 50, 30);

    // --- Patient context ---
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Input Parameters", 20, 55);

    const inputData = [
        ["Temperature", `${formData.temperature}°C`],
        ["Humidity", `${formData.humidity}%`],
        ["Rainfall", `${formData.rainfall}mm`],
        ["AQI", formData.aqi],
        ["Location", formData.location || "N/A"],
    ];

    doc.autoTable({
        startY: 60,
        head: [["Parameter", "Value"]],
        body: inputData,
        theme: 'grid',
        headStyles: { fillColor: [59, 130, 246] },
        styles: { fontSize: 10 },
        margin: { left: 20 },
        tableWidth: 80
    });

    // --- Prediction Request ---
    doc.setFontSize(16);
    doc.text("Prediction Result", 120, 55);

    // Draw Box for Result
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.5);
    doc.rect(120, 60, 70, 40);

    doc.setFontSize(12);
    doc.text("Potential Impact:", 125, 70);

    doc.setFontSize(18);
    doc.setTextColor(220, 20, 60); // Red
    doc.setFont("helvetica", "bold");
    doc.text(result.disease, 125, 80);

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.text(`Model Confidence: ${result.accuracy}%`, 125, 90);

    let currentY = 110;

    // --- Alerts Section (if any) ---
    if (alerts && alerts.length > 0) {
        doc.setFillColor(255, 240, 240);
        doc.rect(20, currentY, pageWidth - 40, 25 + (alerts.length * 5), "F");

        doc.setFontSize(14);
        doc.setTextColor(220, 20, 60);
        doc.setFont("helvetica", "bold");
        doc.text("⚠️ Active Early Warnings", 25, currentY + 10);

        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        alerts.forEach((alert, i) => {
            doc.text(`• ${alert.type}: ${alert.message}`, 25, currentY + 20 + (i * 6));
        });
        currentY += 40 + (alerts.length * 5);
    }

    // --- Forecast Table ---
    if (forecastData && forecastData.length > 0) {
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("7-Day Forecast & Risk Trend", 20, currentY);

        const forecastRows = forecastData.map(day => [
            day.date,
            `${day.temp.toFixed(1)}°C`,
            day.disease_risk_score > 70 ? "High" : day.disease_risk_score > 40 ? "Moderate" : "Low",
            `${day.disease_risk_score}%`
        ]);

        doc.autoTable({
            startY: currentY + 5,
            head: [["Date", "Temp", "Risk Level", "Risk Score"]],
            body: forecastRows,
            theme: 'striped',
            headStyles: { fillColor: [40, 40, 40] },
            margin: { left: 20, right: 20 }
        });

        currentY = doc.lastAutoTable.finalY + 20;
    }

    // --- Footer ---
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Climate Disease Predictor. This is an AI assessment, not a medical diagnosis.", pageWidth / 2, 280, { align: "center" });
    doc.text("Consult a healthcare professional for advice.", pageWidth / 2, 285, { align: "center" });

    // Save
    doc.save(`Medical_Report_${Date.now()}.pdf`);
};

export default generateReport;
